language: python
python:
  - "3.7"
env:
  global:
  - COMMIT_AUTHOR_EMAIL=travis-ci@w3.org

install:
  - pip install bikeshed
  - bikeshed update

script:
  - mkdir out
  - bikeshed spec index.bs out/index.html

before_deploy:
- openssl aes-256-cbc -K $encrypted_1b3d4239d007_key -iv $encrypted_1b3d4239d007_iv
  -in deploy_key.enc -out deploy_key -d

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
